version: '2'
services:
  # django
  weather-app:
    image: weather-app/dev
    container_name: weather-app
    entrypoint: sh docker-entrypoint.sh
    depends_on:
      - postgresql-weather-app
    ports:
      - "8000:8000"
    networks:
      - weather-app-nt
  # postgresql
  postgresql-weather-app:
    image: postgres
    container_name: weather-postgresql
    environment:
      - POSTGRES_PASSWORD=somepwd112233
      - POSTGRES_DB=weather-app
    ports:
      - "5432:5432"
    networks:
      - weather-app-nt

    # celery beat
  celery-weather:
    image: weather-app/dev
    container_name: weather-celery
    entrypoint: celery -A app worker --loglevel=INFO --beat
    depends_on:
      - postgresql-weather-app
      - rabbit-weather
      - redis-weather
    environment:
     - "CELERY=True"
     - "REDIS_HOST=redis-weather"
     - "DB_PASSWORD=somepwd112233"
     - "DB_NAME=weather-app"
     - "DB_HOST=postgresql-weather-app"
    networks:
      - weather-app-nt
  #rabbit
  rabbit-weather:
    hostname: rabbit
    image: rabbitmq:latest
    container_name: weather-rabbit
    networks:
      - weather-app-nt
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
  # redis
  redis-weather:
    image: redis
    container_name: weather-redis
    networks:
      - weather-app-nt

  # Swagger
  swagger:
    image: swaggerapi/swagger-ui
    container_name: weather-app-open-api
    ports:
      - "8001:8080"
    volumes:
    - "../../swagger_spec:/swagger_spec"
    environment:
      SWAGGER_JSON: "/swagger_spec/weather-api-swagger.yaml"
    networks:
      - weather-app-nt

networks:
  weather-app-nt:
    external: true