# Generated by Django 3.0.5 on 2020-04-06 07:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=25)),
                ('country_slug', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityWeatherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status_response', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='logresponse',
            index=models.Index(fields=['log_date', 'status_response'], name='weather_log_log_dat_4278a2_idx'),
        ),
        migrations.AddField(
            model_name='cityweatherlog',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.CityWeather'),
        ),
        migrations.AddField(
            model_name='cityweatherlog',
            name='response_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.LogResponse'),
        ),
        migrations.AddIndex(
            model_name='cityweather',
            index=models.Index(fields=['name', 'slug'], name='weather_cit_name_b44977_idx'),
        ),
        migrations.AddIndex(
            model_name='cityweather',
            index=models.Index(fields=['country_slug'], name='weather_cit_country_64d889_idx'),
        ),
    ]
